mellanox_hpcx_version: "v2.21.2"
rhel8_mellanox_hpcx_package: "hpcx-{{ mellanox_hpcx_version }}-gcc-doca_ofed-redhat8-cuda12-x86_64"
rhel9_mellanox_hpcx_package: "hpcx-{{ mellanox_hpcx_version }}-gcc-doca_ofed-redhat9-cuda12-x86_64"
ubuntu20_mellanox_hpcx_package: "hpcx-{{ mellanox_hpcx_version }}-gcc-doca_ofed-ubuntu20.04-cuda12-x86_64"
ubuntu22_mellanox_hpcx_package: "hpcx-{{ mellanox_hpcx_version }}-gcc-doca_ofed-ubuntu22.04-cuda12-x86_64"
ubuntu24_mellanox_hpcx_package: "hpcx-{{ mellanox_hpcx_version }}-gcc-doca_ofed-ubuntu24.04-cuda12-x86_64"
mellanox_hpcx_download_url: "https://content.mellanox.com/hpc/hpc-x/{{ mellanox_hpcx_version }}"
